CREATE DATABASE ATIVIDADE;

ALTER DATABASE ATIVIDADE
ADD FILEGROUP GA_Geral;


ALTER DATABASE ATIVIDADE
ADD FILE(
	NAME = 'GERAL',
	FILENAME = '/var/opt/mssql/data/Geral.ndf',
	SIZE = 100MB,
	FILEGROWTH = 10MB
) TO FILEGROUP GA_Geral;


ALTER DATABASE ATIVIDADE
MODIFY FILEGROUP GA_Geral DEFAULT;


CREATE TABLE ALUNO(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(150) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	SEXO CHAR(1) NOT NULL
);

ALTER TABLE ALUNO
ADD CONSTRAINT CK_SEXO_ALUNO
CHECK (SEXO IN('M', 'F'));

CREATE TABLE ENDERECO(
	ID INT PRIMARY KEY IDENTITY(1,1),
	RUA VARCHAR(100) NOT NULL,
	NUMERO INT NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
	UF CHAR(2) NOT NULL,
	IDALUNO INT NOT NULL
);

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ALUNO_ENDERECO
FOREIGN KEY (IDALUNO) REFERENCES ALUNO(ID);


ALTER TABLE ENDERECO
ADD CONSTRAINT UQ_ALUNO_ENDERECO
UNIQUE (IDALUNO);

INSERT ALUNO VALUES('ANDRÉ', 'ANDRE@GMAIL.COM', '2006/06/29', 'M');
INSERT ALUNO VALUES('MARCELA', 'MARCELA@GMAIL.COM', '2004/11/12', 'F');
INSERT ALUNO VALUES('RICARDO', 'RICARDO@GMAIL.COM', '1995/02/11', 'M');
INSERT ALUNO VALUES('ANGELA', 'ANGELA@GMAIL.COM', '2000/12/31', 'F');
INSERT ALUNO VALUES('ALBERTO', 'ALBERTO@GMAIL.COM', '1988/01/22', 'M');

SELECT * FROM ALUNO;

INSERT ENDERECO VALUES('Antônio Fagundes', 12,'Vice King', 'União da Vitoria', 'PR', 1);
INSERT ENDERECO VALUES('Astolfo Macedo de Souza', 632,'Centro', 'União da Vitoria', 'PR', 2);
INSERT ENDERECO VALUES('Avenida Marechal Teodoro da Fonseca', 321,'Centro', 'Porto União', 'SC', 3);
INSERT ENDERECO VALUES('Anildo Lindson', 462,'Escondidinho', 'Irineopolis', 'SC', 4);


SELECT * FROM ENDERECO;

CREATE TABLE TELEFONE(
	ID INT UNIQUE IDENTITY,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(12) NOT NULL,
	IDALUNO INT
);

ALTER TABLE TELEFONE 
ADD CONSTRAINT CK_TIPOTELEFONE
CHECK (TIPO IN('CEL','COM','RES'));

ALTER TABLE TELEFONE 
ADD CONSTRAINT PK_TELEFONE
PRIMARY KEY (ID);

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_ALUNO
FOREIGN KEY(IDALUNO) REFERENCES ALUNO(ID);

SP_HELP TELEFONE;

INSERT TELEFONE VALUES('CEL', '42988709103', 1);
INSERT TELEFONE VALUES('COM', '40028922', 1);
INSERT TELEFONE VALUES('CEL', '4198879013', 2);
INSERT TELEFONE VALUES('CEL', '47988190321', 3);
INSERT TELEFONE VALUES('CEL', '42932702198', 4);

SELECT A.NOME, 
B.CIDADE,
ISNULL(C.NUMERO, 'SEM TELEFONE') AS 'TELEFONE',
ISNULL(C.TIPO, 'SEM TELEFONE' )AS 'TIPO TELEFONE', 
A.EMAIL, A.NASCIMENTO
FROM ALUNO A
LEFT JOIN TELEFONE C
ON A.ID = C.IDALUNO
INNER JOIN ENDERECO B
ON A.ID = B.IDALUNO;

SELECT NOME, DATEDIFF(YEAR, NASCIMENTO, GETDATE()) AS IDADE
FROM ALUNO;

SELECT NOME, (DATEDIFF(DAY, NASCIMENTO, GETDATE()) / 365) AS IDADE
FROM ALUNO;



CREATE FUNCTION dbo.dataBR (@DATACONV DATE)
RETURNS CHAR(10)
AS
BEGIN
    RETURN		
    	CAST(DAY(@DATACONV) AS VARCHAR(2)) + '/' +
        CAST(MONTH(@DATACONV) AS VARCHAR(2)) + '/' +
        CAST(YEAR(@DATACONV) AS VARCHAR(4));
END;


SELECT dbo.dataBR(NASCIMENTO) AS DATA
FROM ALUNO;

SELECT NOME, charindex('A', NOME, 0) AS "index" FROM ALUNO;

CREATE TABLE LANCAMENTOCONTABIL(
	CONTA INT NOT NULL,
	VALOR INT NOT NULL,
	TIPO VARCHAR(5) NOT NULL 
);



SELECT * FROM LANCAMENTOCONTABIL;

BULK INSERT LANCAMENTOCONTABIL
FROM '/var/opt/mssql/data/CONTAS.txt'
WITH (
	FIRSTROW = 2, -- DEFINIMOS A PRIMEIRA LINHA COMO SEGUNDA PARA NAO IMPORTAR O CABEÇALHO JUNTO 
	DATAFILETYPE = 'char', -- O QUE TEM NO ARQUIVO
	FIELDTERMINATOR = '\t', -- OS CAMPOS TERMINAM EM?? "\t" equivale ao TAB, pode ser qualquer outro valor
	ROWTERMINATOR = '\n' -- CADA LINHA TERMINA EM?? "\n" equivale ao ENTER. Vem da tabela ASCII 
 );	
 
 -- INSERÇÃO EM MASSA A PARTIR DE UM ARQUIVO!


SELECT DEVE.CONTA, SALDO.VALOR - DEVE.VALOR SALDO
FROM
	(SELECT CONTA, VALOR FROM 
	(
		SELECT CONTA, VALOR, 
		CHARINDEX('D', TIPO) AS DEB
		FROM LANCAMENTOCONTABIL
	) SALDO
	WHERE DEB = 1) SALDO
INNER JOIN
	(SELECT CONTA, VALOR FROM 
	(
		SELECT CONTA, VALOR, 
		CHARINDEX('C', TIPO) CRED
		FROM LANCAMENTOCONTABIL
	) DEVE
WHERE CRED = 1) DEVE
ON DEVE.CONTA = SALDO.CONTA;

